config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  root 'user_files#landing'
  resources :user_files
end

app/models/user_file.rb
class UserFile < ActiveRecord::Base
  has_attached_file :media

  after_create :fetch_torrent
  after_create :fetch_magnet

  validates_attachment :media, content_type:
    { :content_type =>
      [ "image/jpeg",
        "image/gif",
        "image/png",
        "video/avi",
        "video/mpeg",
        "video/m4v",
        "audio/aiff",
        "audio/x-aiff",
        "audio/midi",
        "audio/mpeg",
        "audio/x-mpeg",
        "audio/wav",
        "audio/mpeg3",
        "audio/mp3",
        "audio/x-mp3",
        "application/octet-stream",
        "application/x-bittorrent",
        "application/torrent"
        ]
    }

    # listen to directory changes and stream to S3
    def listen_path
      # Dir should be a constant
      new_dir = ''
      listener = Listen.to(ENV['BASE_MEDIA_PATH']) do |modified, added, removed|
        new_dir = added
        Rails.logger.debug added
      end

      Rails.logger.debug  new_dir
    end

    def fetch_torrent
      if self.media_content_type == "application/octet-stream"
        # raise self.inspect
        torrent = self.media.url.split("?")
        Rails.logger.debug torrent[0]
        begin
          exec("transmission-remote -a #{torrent[0]}")
        rescue
          puts "couldn't connect to server"
        end
      end
    end

    def fetch_magnet
      # byebug

      s3 = AWS::S3.new
      bucket = s3.buckets["hifive-web"]
      obj = bucket.objects["user_files"]

      Rails.logger.debug self.inspect

      if self.url
        system "mkdir #{ENV['BASE_MEDIA_PATH']}/#{self.name}"

        TorrentWorker.perform_async("webtorrent download '#{self.url}' -o '#{ENV['BASE_MEDIA_PATH']}/#{self.name}'")
        AwsWorker.perform_async(obj.write(Pathname.new("#{ENV['BASE_MEDIA_PATH']}/#{self.name}")))
      end
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController

  def index
    @user_files = UserFile.all
  end

  def new
    @user_file = UserFile.new
  end

  def edit
  end

  def show
    @user_file = UserFile.find(params[:id])
  end

  def create
    # raise params.inspect
    @user_file = UserFile.new(file_params)

    respond_to do |format|
      if @user_file.save
        format.html { redirect_to @user_file, notice: "#{@user_file.name} was successfully created." }
        format.json { render :show, status: :created, location: @user_file }
      else
        format.html { render :new, notice: "file save errors: #{@user_file.errors}" }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  def file_params
    params.require(:user_file).permit(:name, :url, :media)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/files/index.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %a.navbar-brand
        YodaFile
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          %a(href="#") hello
        %li
          %a(href="#") world

.container
  .jumbotron
    %h1 All the filez
    .stuff
      here is some stuff
      .more-stuff
        here is more stuff

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>hifive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "partials/nav" %>

  <div class="container">
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/partials/_nav.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to "hifive", root_path, :class => "navbar-brand"
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to "New upload", new_user_file_path
        %li
          = link_to "My files", user_files_path

app/views/user_files/index.html.haml
%h2 my files
%ul.list-group
  - @user_files.each do |file|
    %li.list-group-item
      = link_to "#{file.name}", user_file_path(file.id)

app/views/user_files/landing.html.haml
.container
  .jumbotron
    %h1 welcome to hifive
    %h2 a remote torrent server

app/views/user_files/new.html.haml
.container
  .new-form
    = form_for :user_file, url: user_files_path, html: { :class => "form-horizontal"} do |form|
      .form-group
        = form.label :name, :class => "control-label"
        = form.text_field :name, :class => "form-control"
      .form-group
        = form.label :magnet, :class => "control-label"
        = form.text_field :url, :class => "form-control"
      .form-group
        = form.file_field :media, :class => "form-control"
      .form-group
        = form.submit 'upload', :class => "btn btn-default"

app/views/user_files/show.html.haml
.info
  %h2= @user_file.media_file_name
  %p= @user_file.media
  - if @user_file.media_content_type && @user_file.media_content_type[:image]
    = image_tag @user_file.media, :controls => true
  - else
    = video_tag @user_file.media, :controls => true